//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_Magic_StudentEntities : DbContext
    {
        public DB_Magic_StudentEntities()
            : base("name=DB_Magic_StudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Master_District> tbl_Master_District { get; set; }
        public DbSet<tbl_Master_SchoolYear> tbl_Master_SchoolYear { get; set; }
        public DbSet<tbl_Master_Services> tbl_Master_Services { get; set; }
        public DbSet<tbl_Master_Student> tbl_Master_Student { get; set; }
        public DbSet<tbl_Master_StudentEnrollment> tbl_Master_StudentEnrollment { get; set; }
        public DbSet<tbl_Master_StudentServices> tbl_Master_StudentServices { get; set; }
    
        public virtual ObjectResult<PROC_Get_District_Result> PROC_Get_District()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Get_District_Result>("PROC_Get_District");
        }
    
        public virtual ObjectResult<PROC_Get_SchoolYear_Result> PROC_Get_SchoolYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Get_SchoolYear_Result>("PROC_Get_SchoolYear");
        }
    
        public virtual ObjectResult<PROC_GetStudentDetail_Result> PROC_GetStudentDetail(Nullable<decimal> districtID)
        {
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetStudentDetail_Result>("PROC_GetStudentDetail", districtIDParameter);
        }
    
        public virtual ObjectResult<PROC_GetStudentEnrollmentDetail_Result> PROC_GetStudentEnrollmentDetail(Nullable<decimal> studentID, Nullable<decimal> schoolYearID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var schoolYearIDParameter = schoolYearID.HasValue ?
                new ObjectParameter("SchoolYearID", schoolYearID) :
                new ObjectParameter("SchoolYearID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetStudentEnrollmentDetail_Result>("PROC_GetStudentEnrollmentDetail", studentIDParameter, schoolYearIDParameter);
        }
    
        public virtual ObjectResult<PROC_GetStudentServiceDetail_Result> PROC_GetStudentServiceDetail(Nullable<decimal> studentID, Nullable<decimal> schoolYearID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var schoolYearIDParameter = schoolYearID.HasValue ?
                new ObjectParameter("SchoolYearID", schoolYearID) :
                new ObjectParameter("SchoolYearID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetStudentServiceDetail_Result>("PROC_GetStudentServiceDetail", studentIDParameter, schoolYearIDParameter);
        }
    }
}
