//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_StudentServices
    {
        public decimal ServiceID { get; set; }
        public Nullable<decimal> RefStudentId { get; set; }
        public Nullable<decimal> RefServiceID { get; set; }
        public Nullable<decimal> RefSchoolYearID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IsActive { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<decimal> InsertedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<decimal> ModifyBy { get; set; }
    }
}
